### PR TITLE
event listener destroy function against memory leaks

### PR DESCRIPTION
**Pull request by linus-amg**
hey, i supplied a memory leak test and a fix.

when the html element which scrollspy is used on ($container) gets removed, a reference to the node is still attached, so i wrote some function to destroy the event listeners before removing the html element, like that there is no memory leak anymore.

the api is maybe not the finest but i wanted to introduce a function like that quickly, since i use scrollspy heavily and needed to fix that memory leak.

you can run the test with npm test, drool is a memory leak testing module written by @samccone

### CODE REVIEW

**Comment by linus-amg** [comment]
if you want the test to fail, just remove the 'destroy' function got introduced .. and you'll see that the node count does not match.

**Comment by samccone** [comment]
Woah this is amazing @elgubenis :a: :heavy_plus_sign:

**Comment by softwarespot** [comment]
Thanks @elgubenis for that. I totally forgot to add a destroy action. Also cheers for taking an interest in my fork =)

**Comment by softwarespot** [comment]
I will make a couple of small changes e.g. re-create the minified version

**Comment by samccone** [comment]
@softwarespot if you added travis, this could run automagically :)

**Comment by softwarespot** [comment]
I was mistaken, it was already done. Yeah good idea about travis. Cheers @samccone

**Pull request merged**
